version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    restart: on-failure
    depends_on:
      - backend
    networks:
      - transcendence
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    tty: true
    ports:
      - 3333:3333
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    restart: on-failure
    depends_on:
      dev-db:
        condition: service_healthy
    networks:
      - transcendence
  dev-db:
    container_name: ft_transcendence-dev-db-1
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest
    networks:
      - transcendence
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "admin",
          "-d",
          "nest",
          "-h",
          "localhost",
          "-p",
          "5432",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
networks:
  transcendence:
